// 生成 src/version.generated.js —— 版本号单一来源: package.json + git
// 用法: node scripts/gen-version.mjs
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

function sh(cmd) {
  try { return execSync(cmd, { cwd: root, encoding: 'utf8' }).trim(); }
  catch { return ''; }
}

const version = pkg.version || '0.0.0';
const tag = sh('git describe --tags --abbrev=0 2>/dev/null') || '';
const describe = sh('git describe --tags --always 2>/dev/null') || `v${version}`;
const commit = sh('git rev-parse --short HEAD 2>/dev/null') || 'none';
const dirty = sh('git status --porcelain 2>/dev/null') ? true : false;
const buildTime = new Date().toISOString();

const out = `// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT.
// 版本号单一来源: package.json version + git tag/commit。
// 执行 "npm run version:gen" 重新生成。
export const APP_VERSION = "${version}";
export const APP_TAG = "${tag}";
export const APP_COMMIT = "${commit}";
export const APP_DESCRIBE = "${describe}";
export const APP_DIRTY = ${dirty};
export const APP_BUILD_TIME = "${buildTime}";
`;

writeFileSync(join(root, 'src', 'version.generated.js'), out);
console.log(`version.generated.js -> v${version} | ${describe} | ${commit}${dirty ? ' (dirty)' : ''}`);
